name: Deploy Azure Billing Setup
on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r main/myrequirements.txt

    - name: Deploy Azure Function
      uses: Azure/functions-action@v1
      with:
        app-name: YOUR_FUNCTION_APP_NAME
        package: main
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

